[chain]
rpc_url = "ws://127.0.0.1:9944"

[meilisearch]
host = "http://192.168.2.33:7700"
apikey = "masterKey"

[redis]
# redis://usrname:password@ipaddress:6379/0
url = "redis://:password@127.0.0.1/0" #password

[log]
log_dir = "logs/"
log_cup = 1000
temp_size = "100MB"
zip_compress = true
rolling_type = "All"
level = "info"
debug = true
max_size = "1024MB"
file_name = "explorer.log"

